### ISSUE TITLE
Error al correr nutch

### ISSUE THREAD

**Issue by iorch** [mxabierto/gob.crawler#4]
```
bin/crawl -i -D solr.server.url=http://localhost:8983/solr/crawler urls/ crawler/ 1
Injecting seed URLs
/apache-nutch-1.10/bin/nutch inject crawler//crawldb urls/
Injector: starting at 2015-10-05 17:14:32
Injector: crawlDb: crawler/crawldb
Injector: urlDir: urls
Injector: Converting injected urls to crawl db entries.
Injector: java.io.IOException: Job failed!
	at org.apache.hadoop.mapred.JobClient.runJob(JobClient.java:1357)
	at org.apache.nutch.crawl.Injector.inject(Injector.java:323)
	at org.apache.nutch.crawl.Injector.run(Injector.java:379)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.nutch.crawl.Injector.main(Injector.java:369)

Error running:
  /apache-nutch-1.10/bin/nutch inject crawler//crawldb urls/
Failed with exit value 255.
```

**Comment by iorch** [comment]
Ya encontré el problema:
+ Tengo una lista con las urls que causan problemas con nutch, la forma de evitar esos problemas es agregar las ***regex*** adecuadas en una lista en el archivo `conf/regex-urlfilter.txt` de la siguiente forma:
```
#Skip social media and wikis
-^https://instagram.com/*
-^https://twitter.com/*
-^https://*facebook.com/*
-^https://www.youtube.com/*
-^https://www.pinterest.com/*
-^https://www.flickr.com/
-^http://wikiguias.*
-^http://opendefinition.org/*
-^http://posgrados.cicese.mx/*
-^http://www.bancomext.com/*
-^http://www.cimav.edu.mx/*
-.*acciones-y-programas/centro-de-estudios-superiores-navales*
```

Sin embargo, en la última linea tenía  "-*acciones-y-programas/centro-de-estudios-superiores-navales*", y eso er la causa del error. Lo averigüé leyendo los archivos en la carpeta logs, en la carpeta de nutch.
